"""
Publish daily briefing to web.

Generates HTML briefing and saves to briefings/ directory.
Updates index.html with latest briefing.
"""

import os
import sys
from pathlib import Path
from datetime import datetime
from agents.html_reporter import HTMLReporter


def publish_daily_briefing(db_path: str = "ai_pulse.db", days_back: int = 1, min_score: int = 40):
    """
    Generate and publish daily briefing.

    Args:
        db_path: Database path
        days_back: Days to look back
        min_score: Minimum significance score
    """
    print("=" * 80)
    print("AI-PULSE: Publishing Daily Briefing")
    print("=" * 80)

    # Create briefings directory
    briefings_dir = Path("briefings")
    briefings_dir.mkdir(exist_ok=True)

    # Get current date
    date_str = datetime.utcnow().strftime('%Y-%m-%d')

    # Generate HTML briefing
    print("\n1. Generating HTML briefing...")
    reporter = HTMLReporter(db_path=db_path)
    html, sentiment_counts = reporter.generate_briefing(days_back=days_back, min_score=min_score)

    # Save daily sentiment to database
    print("2. Saving daily sentiment aggregates...")
    from storage.db import EventDatabase
    db = EventDatabase(db_path=db_path)
    db.save_daily_sentiment(date_str, sentiment_counts)
    db.close()

    reporter.close()

    # Save to dated file
    briefing_path = briefings_dir / f"{date_str}.html"

    print(f"3. Saving briefing: {briefing_path}")
    with open(briefing_path, 'w') as f:
        f.write(html)

    # Update index.html with latest briefing
    print("4. Updating index.html...")
    update_index(briefing_path, date_str)

    # Update archive.html
    print("5. Updating archive.html...")
    update_archive()

    print("\n" + "=" * 80)
    print(f"✓ Briefing published: {briefing_path}")
    print(f"✓ View at: file://{briefing_path.absolute()}")
    print("=" * 80)


def update_index(latest_briefing_path: Path, date_str: str):
    """Update index.html - copy latest briefing with updated nav"""

    # Read latest briefing content
    with open(latest_briefing_path, 'r') as f:
        content = f.read()

    # Update navigation to point to correct relative paths
    # (briefing pages have ../ prefix, index.html doesn't need it)
    content = content.replace('href="../style.css"', 'href="style.css"')
    content = content.replace('href="../index.html"', 'href="index.html"')
    content = content.replace('href="../archive.html"', 'href="archive.html"')

    # Write as index.html
    with open('index.html', 'w') as f:
        f.write(content)


def update_archive():
    """Update archive.html with list of all briefings"""

    briefings_dir = Path("briefings")
    briefings = sorted(briefings_dir.glob("*.html"), reverse=True)

    briefings_html = ""
    for briefing_path in briefings:
        date_str = briefing_path.stem
        briefings_html += f"""
            <li>
                <a href="briefings/{briefing_path.name}">
                    <span class="date">{date_str}</span>
                    <span class="arrow">→</span>
                </a>
            </li>
"""

    archive_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI-Pulse Archive - All Briefings</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>🧠 AI-Pulse Archive</h1>
        <p class="tagline">All past briefings</p>
        <nav>
            <a href="index.html">Latest</a>
            <a href="archive.html" class="active">Archive</a>
            <a href="https://github.com/YOUR_USERNAME/ai-pulse">GitHub</a>
        </nav>
    </header>

    <main>
        <section class="archive-list">
            <h2>Past Briefings ({len(briefings)} total)</h2>
            <ul class="briefing-list">
{briefings_html}
            </ul>
        </section>
    </main>

    <footer>
        <p>Generated by AI-Pulse | Data from Hacker News, NewsAPI, SEC EDGAR, GitHub, Company IR</p>
        <p>Analysis powered by Claude (Anthropic)</p>
    </footer>
</body>
</html>
"""

    with open('archive.html', 'w') as f:
        f.write(archive_html)


# CLI
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Publish daily briefing')
    parser.add_argument('--days', type=int, default=1,
                       help='Days to look back (default: 1)')
    parser.add_argument('--min-score', type=int, default=40,
                       help='Minimum significance score (default: 40)')
    parser.add_argument('--db', type=str, default='ai_pulse.db',
                       help='Database path (default: ai_pulse.db)')

    args = parser.parse_args()

    publish_daily_briefing(
        db_path=args.db,
        days_back=args.days,
        min_score=args.min_score
    )
