"""
Regenerate HTML files from existing database data.

SAFE FOR WEB CHANGES - Does NOT:
- Collect new data
- Log predictions
- Update sentiment aggregates
- Touch any database tables

ONLY:
- Reads from database
- Generates HTML files (index.html, archive.html, briefings/*.html)

Use this when:
- Updating navigation, styles, or layout
- Fixing HTML templates
- Making web-only changes

DO NOT use this for:
- Daily data collection (use scheduled workflows)
- Logging predictions (use scheduled workflows)
"""

import sys
from pathlib import Path
from datetime import datetime
from agents.html_reporter import HTMLReporter


def regenerate_html(db_path: str = "ai_pulse.db", days_back: int = 7, min_score: int = 40):
    """
    Regenerate HTML files from existing database data.

    Args:
        db_path: Database path
        days_back: Days to look back for events
        min_score: Minimum significance score
    """
    print("=" * 80)
    print("REGENERATING HTML (READ-ONLY)")
    print("=" * 80)
    print("\n⚠️  This script does NOT:")
    print("   - Collect new data")
    print("   - Log predictions")
    print("   - Update database")
    print("\n✓ This script ONLY:")
    print("   - Reads from database")
    print("   - Generates HTML files")
    print("\n" + "=" * 80 + "\n")

    # Create briefings directory
    briefings_dir = Path("briefings")
    briefings_dir.mkdir(exist_ok=True)

    # Get current date
    date_str = datetime.utcnow().strftime('%Y-%m-%d')

    # Generate HTML briefing
    print("1. Generating HTML briefing from existing data...")
    reporter = HTMLReporter(db_path=db_path)
    html, sentiment_counts = reporter.generate_briefing(days_back=days_back, min_score=min_score)
    reporter.close()

    # Save to dated file
    briefing_path = briefings_dir / f"{date_str}.html"
    print(f"2. Saving briefing: {briefing_path}")
    with open(briefing_path, 'w') as f:
        f.write(html)

    # Update index.html with latest briefing
    print("3. Updating index.html...")
    update_index(briefing_path, date_str)

    # Update archive.html
    print("4. Updating archive.html...")
    update_archive()

    print("\n" + "=" * 80)
    print(f"✓ HTML regenerated from existing database data")
    print(f"✓ View at: file://{briefing_path.absolute()}")
    print("\n⚠️  NO database changes made")
    print("⚠️  NO predictions logged")
    print("=" * 80)


def update_index(latest_briefing_path: Path, date_str: str):
    """Update index.html - copy latest briefing with updated nav"""

    # Read latest briefing content
    with open(latest_briefing_path, 'r') as f:
        content = f.read()

    # Update navigation to point to correct relative paths
    # (briefing pages have ../ prefix, index.html doesn't need it)
    content = content.replace('href="../style.css"', 'href="style.css"')
    content = content.replace('href="../about.html"', 'href="about.html"')
    content = content.replace('href="../index.html"', 'href="index.html"')
    content = content.replace('href="../archive.html"', 'href="archive.html"')

    # Write as index.html
    with open('index.html', 'w') as f:
        f.write(content)


def update_archive():
    """Update archive.html with list of all briefings"""

    briefings_dir = Path("briefings")
    briefings = sorted(briefings_dir.glob("*.html"), reverse=True)

    briefings_html = ""
    for briefing_path in briefings:
        date_str = briefing_path.stem
        briefings_html += f"""
            <li>
                <a href="briefings/{date_str}.html">{date_str}</a>
            </li>"""

    archive_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI-Pulse Archive</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <div class="header-stats">
            <div class="stat-item">
                <span class="stat-value-small">{len(briefings)}</span>
                <span class="stat-label-small">Briefings</span>
            </div>
        </div>

        <div class="header-center">
            <h1>🧠 AI-Pulse</h1>
            <p class="date">Archive</p>
        </div>

        <nav class="header-nav">
            <a href="about.html">About</a>
            <a href="index.html">Latest</a>
            <a href="archive.html" class="active">Archive</a>
            <a href="https://github.com/mat-e-exp/ai-pulse-briefings">GitHub</a>
        </nav>
    </header>

    <main>
        <section class="archive-list">
            <h2>All Briefings</h2>
            <ul>{briefings_html}
            </ul>
        </section>
    </main>

    <footer>
        <p>Generated by AI-Pulse | <a href="https://github.com/mat-e-exp/ai-pulse">Source</a></p>
    </footer>
</body>
</html>"""

    with open('archive.html', 'w') as f:
        f.write(archive_html)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description='Regenerate HTML from existing database (READ-ONLY)',
        epilog='This script does NOT collect data or log predictions. Safe for web changes.'
    )
    parser.add_argument('--db', type=str, default='ai_pulse.db',
                       help='Database path (default: ai_pulse.db)')
    parser.add_argument('--days', type=int, default=7,
                       help='Days to look back (default: 7)')
    parser.add_argument('--min-score', type=int, default=40,
                       help='Minimum significance score (default: 40)')

    args = parser.parse_args()

    regenerate_html(db_path=args.db, days_back=args.days, min_score=args.min_score)
